import { PrismaClient, OpportunitySubject, PrizeTier } from "@prisma/client";

const prisma = new PrismaClient();

// Manually curated. Entries marked [verified Aug 2026] had their current-cycle
// dates checked via live web search on 2026-08-13; everything else uses
// well-established program facts (organization, subject, typical grade
// range, general timing pattern) without inventing a specific date or
// dollar figure — see roadmap.md Phase 7 for why. Google Science Fair was
// checked and confirmed defunct (ended 2018), so it's excluded entirely.

type Seed = {
  title: string;
  organization: string;
  description: string;
  url: string;
  subject: OpportunitySubject;
  minGrade?: number;
  maxGrade?: number;
  typicalDeadlineMonth?: number;
  deadlineNote: string;
  prizeTier?: PrizeTier;
  prizeNote?: string;
};

const opportunities: Seed[] = [
  // --- Science / STEM research ---
  {
    title: "Regeneron Science Talent Search",
    organization: "Society for Science",
    description:
      "The most prestigious individual research competition for US high school seniors — submit an original research project and paper.",
    url: "https://www.societyforscience.org/regeneron-sts/",
    subject: OpportunitySubject.SCIENCE,
    minGrade: 12,
    maxGrade: 12,
    typicalDeadlineMonth: 11,
    deadlineNote: "[verified Aug 2026] 2026 cycle application deadline is November 5, 2026.",
    prizeTier: PrizeTier.LARGE,
    prizeNote: "Top awards have historically reached six figures; see official site for current amounts.",
  },
  {
    title: "Regeneron International Science and Engineering Fair (ISEF)",
    organization: "Society for Science",
    description:
      "The world's largest pre-college science competition. Entry is via qualifying at an affiliated regional/state fair, not direct application.",
    url: "https://www.societyforscience.org/isef/",
    subject: OpportunitySubject.SCIENCE,
    minGrade: 9,
    maxGrade: 12,
    typicalDeadlineMonth: 5,
    deadlineNote:
      "[verified Aug 2026] The 2026 fair was held in May 2026 in Phoenix; the next cycle's dates weren't confirmed at write time — check the official site and find your local affiliated fair (qualification typically starts earlier in the school year).",
    prizeTier: PrizeTier.LARGE,
    prizeNote: "Combined awards across categories have exceeded $9 million in recent years.",
  },
  {
    title: "Broadcom MASTERS",
    organization: "Society for Science",
    description: "National science and engineering competition for middle schoolers (grades 6-8).",
    url: "https://www.societyforscience.org/broadcom-masters/",
    subject: OpportunitySubject.SCIENCE,
    minGrade: 6,
    maxGrade: 8,
    typicalDeadlineMonth: 6,
    deadlineNote: "Typically nominates from students who competed at an affiliated science fair earlier in the year — check official site for the current cycle.",
    prizeTier: PrizeTier.MEDIUM,
  },
  {
    title: "eCYBERMISSION",
    organization: "Army Educational Outreach Program",
    description: "Free STEM competition for grades 6-9, team-based, focused on solving a real community problem.",
    url: "https://www.ecybermission.com/",
    subject: OpportunitySubject.STEM,
    minGrade: 6,
    maxGrade: 9,
    typicalDeadlineMonth: 12,
    deadlineNote: "Typically opens in fall with a winter submission deadline — check official site for exact dates.",
    prizeTier: PrizeTier.MEDIUM,
    prizeNote: "Historically offers savings bond awards at state/regional/national levels.",
  },
  {
    title: "USA Biology Olympiad (USABO)",
    organization: "Center for Excellence in Education",
    description: "Biology competition for high schoolers; qualification is via a school-administered open exam.",
    url: "https://www.usabo-trc.org/",
    subject: OpportunitySubject.SCIENCE,
    minGrade: 9,
    maxGrade: 12,
    typicalDeadlineMonth: 3,
    deadlineNote: "Open exam typically administered in spring — check official site for the current year's registration window.",
    prizeTier: PrizeTier.RECOGNITION,
  },
  {
    title: "USA Chemistry Olympiad (USNCO)",
    organization: "American Chemical Society",
    description: "National chemistry exam series that selects the US team for the International Chemistry Olympiad.",
    url: "https://www.acs.org/education/olympiad.html",
    subject: OpportunitySubject.SCIENCE,
    minGrade: 9,
    maxGrade: 12,
    typicalDeadlineMonth: 3,
    deadlineNote: "Local exams typically run in spring — ask your chemistry teacher or check the official site.",
    prizeTier: PrizeTier.RECOGNITION,
  },
  {
    title: "US Physics Olympiad (USAPhO)",
    organization: "American Association of Physics Teachers",
    description: "Physics competition series that selects the US team for the International Physics Olympiad.",
    url: "https://www.aapt.org/physicsteam/",
    subject: OpportunitySubject.SCIENCE,
    minGrade: 9,
    maxGrade: 12,
    typicalDeadlineMonth: 1,
    deadlineNote: "Preliminary exam typically in January — check official site for current dates.",
    prizeTier: PrizeTier.RECOGNITION,
  },
  {
    title: "USA Astronomy and Astrophysics Olympiad (USAAAO)",
    organization: "USAAAO",
    description: "Astronomy competition open to US high school students, online qualifying exam.",
    url: "https://www.usaaao.org/",
    subject: OpportunitySubject.SCIENCE,
    minGrade: 9,
    maxGrade: 12,
    typicalDeadlineMonth: 10,
    deadlineNote: "Qualifying round typically in fall — check official site for current dates.",
    prizeTier: PrizeTier.RECOGNITION,
  },
  {
    title: "National Science Bowl",
    organization: "US Department of Energy",
    description: "Fast-paced quiz-format team science competition, regional then national finals.",
    url: "https://science.osti.gov/wdts/nsb",
    subject: OpportunitySubject.SCIENCE,
    minGrade: 9,
    maxGrade: 12,
    typicalDeadlineMonth: 1,
    deadlineNote: "Regional competitions typically run January-March — check official site for your region.",
    prizeTier: PrizeTier.SMALL,
  },
  {
    title: "National Ocean Sciences Bowl",
    organization: "Consortium for Ocean Leadership",
    description: "Team quiz-bowl competition focused on ocean science.",
    url: "https://www.nosb.org/",
    subject: OpportunitySubject.SCIENCE,
    minGrade: 9,
    maxGrade: 12,
    typicalDeadlineMonth: 2,
    deadlineNote: "Regional bowls typically in February — check official site for your region.",
    prizeTier: PrizeTier.SMALL,
  },
  {
    title: "Envirothon",
    organization: "National Conservation Foundation",
    description: "Team environmental science competition covering soil, aquatics, forestry, and wildlife.",
    url: "https://envirothon.org/",
    subject: OpportunitySubject.SCIENCE,
    minGrade: 9,
    maxGrade: 12,
    typicalDeadlineMonth: 5,
    deadlineNote: "State competitions typically in spring, leading to nationals in summer — check your state's Envirothon chapter.",
    prizeTier: PrizeTier.SMALL,
  },
  {
    title: "Junior Science and Humanities Symposium (JSHS)",
    organization: "Department of Defense",
    description: "Original research symposium for grades 9-12, regional events feed into a national symposium.",
    url: "https://www.jshs.org/",
    subject: OpportunitySubject.SCIENCE,
    minGrade: 9,
    maxGrade: 12,
    typicalDeadlineMonth: 1,
    deadlineNote: "Regional deadlines vary by region, typically winter — check your regional JSHS site.",
    prizeTier: PrizeTier.MEDIUM,
    prizeNote: "Includes scholarship awards at regional and national levels.",
  },

  // --- Math ---
  {
    title: "MATHCOUNTS",
    organization: "MATHCOUNTS Foundation",
    description: "The premier US middle school math competition — school, chapter, state, and national rounds.",
    url: "https://www.mathcounts.org/",
    subject: OpportunitySubject.MATH,
    minGrade: 6,
    maxGrade: 8,
    typicalDeadlineMonth: 10,
    deadlineNote: "School registration typically opens in fall — check official site for the current cycle.",
    prizeTier: PrizeTier.SMALL,
  },
  {
    title: "AMC 8 / 10 / 12 (American Mathematics Competitions)",
    organization: "Mathematical Association of America",
    description: "The standard entry point into the US math olympiad pipeline (AMC -> AIME -> USAMO).",
    url: "https://maa.org/student-programs/amc/",
    subject: OpportunitySubject.MATH,
    minGrade: 6,
    maxGrade: 12,
    typicalDeadlineMonth: 11,
    deadlineNote: "AMC 8 typically in January, AMC 10/12 in November — ask your math teacher about registering your school.",
    prizeTier: PrizeTier.RECOGNITION,
  },
  {
    title: "American Regions Mathematics League (ARML)",
    organization: "ARML",
    description: "Team math competition, one of the largest of its kind in the US.",
    url: "https://www.arml.com/",
    subject: OpportunitySubject.MATH,
    minGrade: 9,
    maxGrade: 12,
    typicalDeadlineMonth: 4,
    deadlineNote: "Competition typically held in late spring, registered through a local team — check official site.",
    prizeTier: PrizeTier.RECOGNITION,
  },

  // --- Engineering / Robotics ---
  {
    title: "FIRST Robotics Competition",
    organization: "FIRST",
    description: "High school robotics competition combining a build season with regional and championship events.",
    url: "https://www.firstinspires.org/robotics/frc",
    subject: OpportunitySubject.ENGINEERING,
    minGrade: 9,
    maxGrade: 12,
    typicalDeadlineMonth: 1,
    deadlineNote: "[verified Aug 2026] Next season (BIOCORE, 2026-27) kicks off January 9, 2027 — team registration typically opens before then.",
    prizeTier: PrizeTier.LARGE,
    prizeNote: "Large aggregate college scholarship pool available to participants.",
  },
  {
    title: "FIRST Tech Challenge",
    organization: "FIRST",
    description: "Robotics competition for grades 7-12, smaller-scale and lower-cost than FRC.",
    url: "https://www.firstinspires.org/robotics/ftc",
    subject: OpportunitySubject.ENGINEERING,
    minGrade: 7,
    maxGrade: 12,
    typicalDeadlineMonth: 9,
    deadlineNote: "Season typically kicks off in fall — check official site for current dates.",
    prizeTier: PrizeTier.MEDIUM,
  },
  {
    title: "FIRST LEGO League",
    organization: "FIRST",
    description: "Robotics and research program for grades 4-8 built around LEGO robotics.",
    url: "https://www.firstinspires.org/robotics/fll",
    subject: OpportunitySubject.ENGINEERING,
    minGrade: 4,
    maxGrade: 8,
    typicalDeadlineMonth: 9,
    deadlineNote: "Season typically kicks off in fall — check official site for current dates.",
    prizeTier: PrizeTier.SMALL,
  },
  {
    title: "VEX Robotics Competition",
    organization: "REC Foundation",
    description: "Global robotics competition series across middle school, high school, and college divisions.",
    url: "https://www.roboticseducation.org/vex-robotics-competition/",
    subject: OpportunitySubject.ENGINEERING,
    minGrade: 6,
    maxGrade: 12,
    typicalDeadlineMonth: 9,
    deadlineNote: "Season typically runs fall through spring with a world championship — check official site for local event dates.",
    prizeTier: PrizeTier.MEDIUM,
  },
  {
    title: "Conrad Challenge",
    organization: "Conrad Foundation",
    description: "Team innovation and entrepreneurship competition for ages 13-18, solving real-world challenges.",
    url: "https://conrad.spacecenter.org/",
    subject: OpportunitySubject.ENGINEERING,
    minGrade: 8,
    maxGrade: 12,
    typicalDeadlineMonth: 8,
    deadlineNote: "[verified Aug 2026] Registration typically opens in late August; the 2025-26 cycle ran through an April 2026 Innovation Summit.",
    prizeTier: PrizeTier.MEDIUM,
  },
  {
    title: "Odyssey of the Mind",
    organization: "Creative Competitions Inc.",
    description: "Creative problem-solving team competition spanning technical, artistic, and improvisational challenges.",
    url: "https://www.odysseyofthemind.com/",
    subject: OpportunitySubject.STEM,
    minGrade: 1,
    maxGrade: 12,
    typicalDeadlineMonth: 9,
    deadlineNote: "Team registration typically opens in fall, competitions in spring — check official site.",
    prizeTier: PrizeTier.SMALL,
  },
  {
    title: "Destination Imagination",
    organization: "Destination Imagination Inc.",
    description: "Creative problem-solving team challenges across STEM, arts, and improv, K-12.",
    url: "https://www.destinationimagination.org/",
    subject: OpportunitySubject.STEM,
    minGrade: 1,
    maxGrade: 12,
    typicalDeadlineMonth: 9,
    deadlineNote: "Team registration typically opens in fall — check official site.",
    prizeTier: PrizeTier.SMALL,
  },

  // --- Computer science ---
  {
    title: "Congressional App Challenge",
    organization: "US House of Representatives",
    description: "District-level app development competition open to middle and high schoolers.",
    url: "https://www.congressionalappchallenge.us/",
    subject: OpportunitySubject.COMPUTER_SCIENCE,
    minGrade: 6,
    maxGrade: 12,
    typicalDeadlineMonth: 10,
    deadlineNote: "[verified Aug 2026] 2026 challenge deadline is October 26, 2026 — check whether your congressional district participates.",
    prizeTier: PrizeTier.RECOGNITION,
    prizeNote: "District winners are recognized by their member of Congress; some districts offer additional prizes.",
  },
  {
    title: "Technovation Girls",
    organization: "Technovation",
    description: "Global technology entrepreneurship program for girls and gender-marginalized youth — build an app addressing a real problem.",
    url: "https://technovationchallenge.org/",
    subject: OpportunitySubject.COMPUTER_SCIENCE,
    minGrade: 5,
    maxGrade: 12,
    typicalDeadlineMonth: 3,
    deadlineNote: "[verified Aug 2026] Registration for the 2026 season closed March 18, 2026; the 2027 season typically opens in August — check official site.",
    prizeTier: PrizeTier.MEDIUM,
  },
  {
    title: "NCWIT Aspirations in Computing",
    organization: "National Center for Women & Information Technology",
    description: "Recognition award for young women and gender-marginalized students in computing.",
    url: "https://www.aspirations.org/",
    subject: OpportunitySubject.COMPUTER_SCIENCE,
    minGrade: 9,
    maxGrade: 12,
    typicalDeadlineMonth: 10,
    deadlineNote: "Applications typically open in fall — check official site for the current cycle.",
    prizeTier: PrizeTier.RECOGNITION,
  },
  {
    title: "Major League Hacking Season Hackathons",
    organization: "Major League Hacking",
    description: "Ongoing series of student-run hackathons throughout the school year, not a single event or deadline.",
    url: "https://mlh.io/seasons/2027/events",
    subject: OpportunitySubject.COMPUTER_SCIENCE,
    minGrade: 9,
    maxGrade: 12,
    deadlineNote: "Rolling — new events added throughout the year. Browse the current season's calendar on MLH's site for dates near you.",
    prizeTier: PrizeTier.UNKNOWN,
    prizeNote: "Varies by individual event.",
  },

  // --- Business / entrepreneurship ---
  {
    title: "DECA",
    organization: "DECA Inc.",
    description: "Business, marketing, finance, and hospitality competitive events, chapter through international levels.",
    url: "https://www.deca.org/",
    subject: OpportunitySubject.BUSINESS,
    minGrade: 9,
    maxGrade: 12,
    typicalDeadlineMonth: 11,
    deadlineNote: "Membership/chapter deadlines are set by individual schools — ask your DECA advisor or check official site.",
    prizeTier: PrizeTier.SMALL,
  },
  {
    title: "FBLA (Future Business Leaders of America)",
    organization: "FBLA-PBL Inc.",
    description: "Business-focused competitive events and leadership program for middle and high schoolers.",
    url: "https://www.fbla.org/",
    subject: OpportunitySubject.BUSINESS,
    minGrade: 6,
    maxGrade: 12,
    typicalDeadlineMonth: 11,
    deadlineNote: "Membership/chapter deadlines are set by individual schools — ask your FBLA advisor or check official site.",
    prizeTier: PrizeTier.SMALL,
  },
  {
    title: "Diamond Challenge",
    organization: "Horn Entrepreneurship, University of Delaware",
    description: "Global entrepreneurship competition for teams of high schoolers to pitch a business or social venture concept.",
    url: "https://diamondchallenge.org/",
    subject: OpportunitySubject.BUSINESS,
    minGrade: 9,
    maxGrade: 12,
    typicalDeadlineMonth: 1,
    deadlineNote: "[verified Aug 2026] The 2026 cycle ran September 2025-January 2026; expect a similar September-January window for the next cycle.",
    prizeTier: PrizeTier.LARGE,
    prizeNote: "Recent prize pools have totaled around $100,000 across tracks and topical awards.",
  },
  {
    title: "National Economics Challenge",
    organization: "Council for Economic Education",
    description: "Team economics competition, school through national levels.",
    url: "https://www.councilforeconed.org/national-economics-challenge/",
    subject: OpportunitySubject.BUSINESS,
    minGrade: 9,
    maxGrade: 12,
    typicalDeadlineMonth: 3,
    deadlineNote: "State/regional rounds typically in spring — check official site.",
    prizeTier: PrizeTier.SMALL,
  },

  // --- Writing / humanities ---
  {
    title: "Scholastic Art & Writing Awards",
    organization: "Alliance for Young Artists & Writers",
    description: "The longest-running, largest recognition program for creative teens in the US, art and writing categories.",
    url: "https://www.artandwriting.org/",
    subject: OpportunitySubject.WRITING,
    minGrade: 7,
    maxGrade: 12,
    typicalDeadlineMonth: 12,
    deadlineNote: "[verified Aug 2026] Entries typically open around October 1 with regional deadlines from December through early January — use the official Region Locator for your exact deadline.",
    prizeTier: PrizeTier.MEDIUM,
    prizeNote: "National medalists are eligible for scholarships.",
  },
  {
    title: "John Locke Institute Essay Competition",
    organization: "John Locke Institute",
    description: "International argumentative essay competition across ten subject categories, widely regarded as one of the most prestigious pre-university writing contests.",
    url: "https://www.johnlocke.org/essay-competition",
    subject: OpportunitySubject.WRITING,
    minGrade: 9,
    maxGrade: 12,
    typicalDeadlineMonth: 5,
    deadlineNote: "[verified Aug 2026] The 2026 registration window was February-April, submissions due May 31, 2026 — expect a similar window next cycle.",
    prizeTier: PrizeTier.LARGE,
    prizeNote: "Grand prize winners have received $10,000 scholarships toward Institute programs.",
  },
  {
    title: "National Council of Teachers of English (NCTE) Achievement Award in Writing",
    organization: "NCTE",
    description: "National writing recognition program nominated through participating schools.",
    url: "https://ncte.org/awards/achievement-award-in-writing/",
    subject: OpportunitySubject.WRITING,
    minGrade: 11,
    maxGrade: 11,
    typicalDeadlineMonth: 2,
    deadlineNote: "Nominated by your school's English department, typically in winter — ask a teacher if your school participates.",
    prizeTier: PrizeTier.RECOGNITION,
  },
  {
    title: "National History Day",
    organization: "National History Day Inc.",
    description: "Year-long research project competition (paper, exhibit, documentary, performance, or website) on an annual theme.",
    url: "https://www.nhd.org/",
    subject: OpportunitySubject.WRITING,
    minGrade: 6,
    maxGrade: 12,
    typicalDeadlineMonth: 3,
    deadlineNote: "District and state contests typically run winter-spring, leading to nationals in June — check your state's NHD affiliate.",
    prizeTier: PrizeTier.MEDIUM,
  },

  // --- Debate / speech ---
  {
    title: "National Speech & Debate Association Tournament Circuit",
    organization: "National Speech & Debate Association",
    description: "The main US high school speech and debate circuit, ongoing tournaments through the school year leading to nationals.",
    url: "https://www.speechanddebate.org/",
    subject: OpportunitySubject.DEBATE,
    minGrade: 9,
    maxGrade: 12,
    deadlineNote: "Rolling — tournaments run throughout the school year via your school's team. Ask your speech/debate coach.",
    prizeTier: PrizeTier.RECOGNITION,
  },
  {
    title: "We the People: The Citizen and the Constitution",
    organization: "Center for Civic Education",
    description: "Simulated congressional hearing competition on constitutional principles, class-based team competition.",
    url: "https://www.civiced.org/we-the-people",
    subject: OpportunitySubject.DEBATE,
    minGrade: 9,
    maxGrade: 12,
    typicalDeadlineMonth: 3,
    deadlineNote: "State competitions typically in winter/spring — check whether your school's civics/government class participates.",
    prizeTier: PrizeTier.RECOGNITION,
  },

  // --- General / multi-subject ---
  {
    title: "Junior Science and Humanities Symposium — Regional Chapters",
    organization: "Department of Defense",
    description: "See national JSHS entry above; many regions run their own qualifying symposium with local deadlines.",
    url: "https://www.jshs.org/regions",
    subject: OpportunitySubject.GENERAL,
    minGrade: 9,
    maxGrade: 12,
    deadlineNote: "Varies by region — find your regional JSHS chapter's site for exact dates.",
    prizeTier: PrizeTier.MEDIUM,
  },
  {
    title: "Model United Nations Conferences",
    organization: "Various (e.g. NHSMUN, university-run conferences)",
    description: "Simulated UN diplomacy conferences run by many universities and organizations throughout the year — not a single competition.",
    url: "https://www.nhsmun.org/",
    subject: OpportunitySubject.GENERAL,
    minGrade: 9,
    maxGrade: 12,
    deadlineNote: "Rolling — individual conferences set their own registration deadlines. Ask if your school has a Model UN club, or search for conferences near you.",
    prizeTier: PrizeTier.RECOGNITION,
  },
  {
    title: "Science Olympiad",
    organization: "Science Olympiad Inc.",
    description: "Team competition across dozens of STEM events per meet, from regional through national tournaments.",
    url: "https://www.soinc.org/",
    subject: OpportunitySubject.STEM,
    minGrade: 6,
    maxGrade: 12,
    typicalDeadlineMonth: 9,
    deadlineNote: "Team registration typically opens in fall, invitational/regional/state meets run winter-spring — check official site.",
    prizeTier: PrizeTier.SMALL,
  },
  {
    title: "American Computer Science League (ACSL)",
    organization: "ACSL",
    description: "Computer science problem-solving and programming contest run in multiple contests across the school year.",
    url: "http://www.acsl.org/",
    subject: OpportunitySubject.COMPUTER_SCIENCE,
    minGrade: 3,
    maxGrade: 12,
    typicalDeadlineMonth: 9,
    deadlineNote: "School registration typically opens in fall for a series of contests through the year — check official site.",
    prizeTier: PrizeTier.RECOGNITION,
  },
  {
    title: "USA Computing Olympiad (USACO)",
    organization: "USACO",
    description: "Free online competitive programming contest series, open year-round with quarterly contests.",
    url: "http://www.usaco.org/",
    subject: OpportunitySubject.COMPUTER_SCIENCE,
    minGrade: 6,
    maxGrade: 12,
    deadlineNote: "Contests run roughly quarterly and are self-paced/online — check official site for the current contest window.",
    prizeTier: PrizeTier.RECOGNITION,
  },
  {
    title: "CyberPatriot",
    organization: "Air Force Association",
    description: "National youth cyber defense competition — teams secure simulated networks against vulnerabilities.",
    url: "https://www.uscyberpatriot.org/",
    subject: OpportunitySubject.COMPUTER_SCIENCE,
    minGrade: 6,
    maxGrade: 12,
    typicalDeadlineMonth: 9,
    deadlineNote: "Team registration typically opens in late summer/fall for a season running into spring — check official site.",
    prizeTier: PrizeTier.MEDIUM,
    prizeNote: "Includes scholarship awards for top finalist teams.",
  },
  {
    title: "International Genius Olympiad",
    organization: "Genius Group",
    description: "Multi-subject international competition (science, engineering, arts, and more) held annually in New York.",
    url: "https://geniusolympiad.org/",
    subject: OpportunitySubject.STEM,
    minGrade: 9,
    maxGrade: 12,
    typicalDeadlineMonth: 2,
    deadlineNote: "Applications typically due in winter for a summer event — check official site for current dates.",
    prizeTier: PrizeTier.MEDIUM,
  },
  {
    title: "National Youth Science Camp",
    organization: "National Youth Science Foundation",
    description: "All-expenses-paid summer program for two graduating seniors selected per state — application through your state's process.",
    url: "https://www.nysc.org/",
    subject: OpportunitySubject.SCIENCE,
    minGrade: 12,
    maxGrade: 12,
    typicalDeadlineMonth: 3,
    deadlineNote: "State selection processes vary — check your state's delegate selection page, typically in winter/spring.",
    prizeTier: PrizeTier.RECOGNITION,
  },
  {
    title: "Poetry Out Loud",
    organization: "National Endowment for the Arts / Poetry Foundation",
    description: "National recitation competition — memorize and perform poetry, classroom through national finals.",
    url: "https://www.poetryoutloud.org/",
    subject: OpportunitySubject.ARTS,
    minGrade: 9,
    maxGrade: 12,
    typicalDeadlineMonth: 1,
    deadlineNote: "Runs through participating schools/states, typically winter — ask an English teacher if your school participates.",
    prizeTier: PrizeTier.SMALL,
  },
  {
    title: "YoungArts",
    organization: "National YoungArts Foundation",
    description: "National recognition and awards program across visual, literary, and performing arts for ages 15-18.",
    url: "https://youngarts.org/",
    subject: OpportunitySubject.ARTS,
    minGrade: 9,
    maxGrade: 12,
    typicalDeadlineMonth: 10,
    deadlineNote: "Applications typically open in summer with a fall deadline — check official site for the current cycle.",
    prizeTier: PrizeTier.MEDIUM,
    prizeNote: "Cash awards and potential nomination as a US Presidential Scholar in the Arts.",
  },
  {
    title: "Regional & State Science Fairs",
    organization: "Varies by state/region",
    description: "Most states and many school districts run their own local science and engineering fairs feeding into ISEF and other national programs.",
    url: "https://www.societyforscience.org/isef/affiliated-fairs/",
    subject: OpportunitySubject.SCIENCE,
    minGrade: 6,
    maxGrade: 12,
    deadlineNote: "Find your affiliated regional fair via the ISEF affiliate directory — dates vary widely by region.",
    prizeTier: PrizeTier.UNKNOWN,
  },
];

async function main() {
  console.log(`Seeding ${opportunities.length} opportunities...`);
  for (const o of opportunities) {
    await prisma.opportunity.create({ data: o });
  }
  console.log("Done.");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
